public class app1 {
    public static void main(String[] args) {
        System.out.println("Interpreter VS Compiler");
        // Interpreter Translate one statement at a time into machine code...
        // Compiler scans the entire program and translate whole of it into machine
        // code...
        // Java is hybrid language: Both Compiled as well as interpreted...
        // Java program is platform independent because it is hybrid language...
    }
}
